global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'procurement-service'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'finance-service'
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'intelligence-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
